### ISSUE TITLE
(v0.9.7) Panic in gorgonia.SoftMax

### ISSUE THREAD

**Issue by dimuls** [gorgonia/gorgonia#373]
I'm building CNN using this code:
```
	n.w0 := gorgonia.NewTensor(g, gorgonia.Float32, 4,
		gorgonia.WithName("w0"),
		gorgonia.WithShape(32, 1, 3, 3),
		gorgonia.WithInit(gorgonia.GlorotN(1.0)))

	n.w1 := gorgonia.NewTensor(g, gorgonia.Float32, 4,
		gorgonia.WithName("w1"),
		gorgonia.WithShape(64, 32, 3, 3),
		gorgonia.WithInit(gorgonia.GlorotN(1.0)))

	n.w2 := gorgonia.NewTensor(g, gorgonia.Float32, 4,
		gorgonia.WithName("w2"),
		gorgonia.WithShape(128, 64, 3, 3),
		gorgonia.WithInit(gorgonia.GlorotN(1.0)))

	n.w3 := gorgonia.NewMatrix(g, gorgonia.Float32,
		gorgonia.WithName("w3"),
		gorgonia.WithShape(128*6*6, w3Size),
		gorgonia.WithInit(gorgonia.GlorotN(1.0)))

	n.w4 := gorgonia.NewMatrix(g, gorgonia.Float32,
		gorgonia.WithName("w4"),
		gorgonia.WithShape(w3Size, outputSize),
		gorgonia.WithInit(gorgonia.GlorotN(1.0)))

<...>

	ints00 := []int{0, 0}
	ints11 := []int{1, 1}
	ints22 := []int{2, 2}

	shape22 := tensor.Shape{2, 2}
	shape33 := tensor.Shape{3, 3}

	// layer 0

	c0, err := gorgonia.Conv2d(input, n.w0, shape33, ints11,
		ints11, ints11)
	if err != nil {
		return nil, fmt.Errorf("c0=Conv2D: %w", err)
	}

	a0, err := gorgonia.Rectify(c0)
	if err != nil {
		return nil, fmt.Errorf("a0=Rectify: %w", err)
	}

	p0, err := gorgonia.MaxPool2D(a0, shape22, ints00, ints22)
	if err != nil {
		return nil, fmt.Errorf("p0=MaxPool2D: %w", err)
	}

	l0, err := gorgonia.Dropout(p0, n.d0)
	if err != nil {
		return nil, fmt.Errorf("l0=Dropout: %w", err)
	}

	// layer 1

	c1, err := gorgonia.Conv2d(l0, n.w1, shape33, ints11, ints11, ints11)
	if err != nil {
		return nil, fmt.Errorf("c1=Conv2D: %w", err)
	}

	a1, err := gorgonia.Rectify(c1)
	if err != nil {
		return nil, fmt.Errorf("a1=Rectify: %w", err)
	}

	p1, err := gorgonia.MaxPool2D(a1, shape22, ints00, ints22)
	if err != nil {
		return nil, fmt.Errorf("p1=MaxPool2D: %w", err)
	}

	l1, err := gorgonia.Dropout(p1, n.d1)
	if err != nil {
		return nil, fmt.Errorf("l1=Dropout: %w", err)
	}

	// layer 2

	c2, err := gorgonia.Conv2d(l1, n.w2, shape33, ints11, ints11, ints11)
	if err != nil {
		return nil, fmt.Errorf("c2=Conv2D: %w", err)
	}

	a2, err := gorgonia.Rectify(c2)
	if err != nil {
		return nil, fmt.Errorf("a2=Rectify: %w", err)
	}

	p2, err := gorgonia.MaxPool2D(a2, shape22, ints00, ints22)
	if err != nil {
		return nil, fmt.Errorf("p2=MaxPool2D: %w", err)
	}

	b, c, h, w := p2.Shape()[0], p2.Shape()[1], p2.Shape()[2], p2.Shape()[3]

	r2, err := gorgonia.Reshape(p2, tensor.Shape{b, c * h * w})
	if err != nil {
		return nil, fmt.Errorf("r2=Reshape: %w", err)
	}

	l2, err := gorgonia.Dropout(r2, n.d2)
	if err != nil {
		return nil, fmt.Errorf("l2=Dropout: %w", err)
	}

	// layer 3

	fc, err := gorgonia.Mul(l2, n.w3)
	if err != nil {
		return nil, fmt.Errorf("fc=Mul: %w", err)
	}

	a3, err := gorgonia.Rectify(fc)
	if err != nil {
		return nil, fmt.Errorf("a3=Rectify: %w", err)
	}

	l3, err := gorgonia.Dropout(a3, n.d3)
	if err != nil {
		return nil, fmt.Errorf("l3=Dropout: %w", err)
	}

	// output

	output, err := gorgonia.Mul(l3, n.w4)
	if err != nil {
		return nil, fmt.Errorf("output=Mul: %w", err)
	}

	output, err = gorgonia.SoftMax(output)
	if err != nil {
		return nil, fmt.Errorf("output=SoftMax: %w", err)
	}

	return output, nil```

Panic occurs in the last `gorgonia.SoftMax` call when my `input` at the beginning has shape `(1, 1, 48, 48)`. If i try to use `input` shape `(2, 1, 48, 48)` (just repeat input two times) then everything seems works.

```panic: Node Σ[1](%3b) :: Vector float32, has 1 dimensions(Shape: ()). Input shape is (), which has 0 dimensions

goroutine 1 [running]:
gorgonia.org/gorgonia.WithShape.func1(0xc0000f4a80)
        /home/vadim/go/pkg/mod/gorgonia.org/gorgonia@v0.9.7/node.go:211 +0x310
gorgonia.org/gorgonia.newNode(0xc000157768, 0x5, 0x5, 0x0)
        /home/vadim/go/pkg/mod/gorgonia.org/gorgonia@v0.9.7/node.go:264 +0x7d
gorgonia.org/gorgonia.NewUniqueNode(0xc000157768, 0x5, 0x5, 0xc00016eb80)
        /home/vadim/go/pkg/mod/gorgonia.org/gorgonia@v0.9.7/node.go:274 +0x43
gorgonia.org/gorgonia.ApplyOp(0xc57e60, 0xc000172340, 0xc0001be4c0, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/vadim/go/pkg/mod/gorgonia.org/gorgonia@v0.9.7/op.go:202 +0x654
gorgonia.org/gorgonia.Sum(0xc0000f49a0, 0xc0001d7d20, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/vadim/go/pkg/mod/gorgonia.org/gorgonia@v0.9.7/operations.go:340 +0x23d
gorgonia.org/gorgonia.SoftMax(0xc0000f48c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vadim/go/pkg/mod/gorgonia.org/gorgonia@v0.9.7/operations.go:179 +0x30b```

**Comment by chewxy** [comment]
I believe this has been fixed in `master`. But I don't believe that there is a release for this yet. Please holdl

**Comment by dimuls** [comment]
Tried latest master (v0.9.8-0.20200207231045-1fda08736b18): doesn't work.

**Comment by chewxy** [comment]
OK working on this - v0.98 was just tagged... 

Do you have the full code so I may reproduce @dimuls ? Thanks

**Comment by dimuls** [comment]
@chewxy same panic.

```panic: Node Σ[1](%49) :: Vector float64, has 1 dimensions(Shape: ()). Input shape is (), which has 0 dimensions

goroutine 1 [running]:
gorgonia.org/gorgonia.WithShape.func1(0xc0000a1880)
        /home/vadim/go/pkg/mod/gorgonia.org/gorgonia@v0.9.8/node.go:211 +0x310
gorgonia.org/gorgonia.newNode(0xc000109330, 0x5, 0x5, 0x0)
        /home/vadim/go/pkg/mod/gorgonia.org/gorgonia@v0.9.8/node.go:264 +0x7d
gorgonia.org/gorgonia.NewUniqueNode(0xc000109330, 0x5, 0x5, 0xc0000edb00)
        /home/vadim/go/pkg/mod/gorgonia.org/gorgonia@v0.9.8/node.go:274 +0x43
gorgonia.org/gorgonia.ApplyOp(0xcbc0a0, 0xc000214680, 0xc00020c570, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/vadim/go/pkg/mod/gorgonia.org/gorgonia@v0.9.8/op.go:202 +0x654
gorgonia.org/gorgonia.Sum(0xc0000a17a0, 0xc000212b20, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/vadim/go/pkg/mod/gorgonia.org/gorgonia@v0.9.8/operations.go:340 +0x23d
gorgonia.org/gorgonia.SoftMax(0xc0000a16c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        /home/vadim/go/pkg/mod/gorgonia.org/gorgonia@v0.9.8/operations.go:179 +0x30e```

**Comment by dimuls** [comment]
@chewxy this is how you can reproduce panic: https://gist.github.com/dimuls/6dfc4ba5f426896c3ac530fde2bd1283

**Comment by owulveryck** [comment]
For information, I am trying to upgrade the Gorgonia dependency in onnx-go, and I am facing the same issue.
I will try to have a look.

**Comment by dcu** [comment]
is this still happening?

**Comment by JensRantil** [comment]
Has there been any progress here?
