### ISSUE TITLE
Panic in gorgonia.Mean

### ISSUE THREAD

**Issue by sanghuynh1501** [gorgonia/gorgonia#375]
i caculated mean of tensor with the shape (1, 64, 1, 64) and it didn't work
```
func main() {
	flag.Parse()
	parseDtype()
	rand.Seed(1337)

	g := gorgonia.NewGraph()

	w0 := gorgonia.NewTensor(g, dt, 4, gorgonia.WithShape(1, 64, 1, 64), gorgonia.WithName("w0"), gorgonia.WithInit(gorgonia.GlorotN(1.0)))
	result, _ := gorgonia.Mean(w0, 3)
	log.Println(result.Shape())
}
```
```
panic: Node Σ[3](%0) :: Tensor-4 float64, has 4 dimensions(Shape: ()). Input shape is (64), which has 1 dimensions

goroutine 1 [running]:
gorgonia.org/gorgonia.WithShape.func1(0xc0000b8fc0)
        /home/sang/go/src/gorgonia.org/gorgonia/node.go:211 +0x310
gorgonia.org/gorgonia.newNode(0xc000113cf0, 0x5, 0x5, 0x1)
        /home/sang/go/src/gorgonia.org/gorgonia/node.go:264 +0x7d
gorgonia.org/gorgonia.NewUniqueNode(0xc000113cf0, 0x5, 0x5, 0xc000142f00)
        /home/sang/go/src/gorgonia.org/gorgonia/node.go:274 +0x43
gorgonia.org/gorgonia.ApplyOp(0xbc8720, 0xc000129ec0, 0xc00000e7e8, 0x1, 0x1, 0x0, 0x0, 0x0)
        /home/sang/go/src/gorgonia.org/gorgonia/op.go:202 +0x654
gorgonia.org/gorgonia.Sum(0xc0000b8ee0, 0xc00012d7f8, 0x1, 0x1, 0x6, 0xc000144960, 0xc000142a00)
        /home/sang/go/src/gorgonia.org/gorgonia/operations.go:340 +0x23d
gorgonia.org/gorgonia.Mean(0xc0000b8ee0, 0xc00012d7f8, 0x1, 0x1, 0xc000113f38, 0x3, 0x3)
        /home/sang/go/src/gorgonia.org/gorgonia/operations.go:300 +0x90
main.main()
        /home/sang/go/src/test_mean_gorgonia/main.go:37 +0x282
exit status 2
```
but when i changed the shape to  (1, 64, 1, 64) it worked
```
flag.Parse()
	parseDtype()
	rand.Seed(1337)

	g := gorgonia.NewGraph()

	w0 := gorgonia.NewTensor(g, dt, 4, gorgonia.WithShape(1, 64, 2, 64), gorgonia.WithName("w0"), gorgonia.WithInit(gorgonia.GlorotN(1.0)))
	result, _ := gorgonia.Mean(w0, 3)
	log.Println(result.Shape())
```
```
2020/02/10 11:53:14 (1, 64, 2, 1)
```

**Comment by chewxy** [comment]
Related to #373 .. please hold.

**Comment by owulveryck** [comment]
Is this issue still relevant?

**Comment by wzzhu** [comment]
There is no problem with Mean. This issue should be closed.
