### ISSUE TITLE
Unable to run covnet_cuda example

### ISSUE THREAD

**Issue by dimuls** [gorgonia/gorgonia#376]
CUDA example from readme i was able to successfully run. But when i run covnet example i'm getting errors:
```
2020/02/11 18:16:00 Using CUDA build
2020/02/11 18:16:00 gorgonia. true
2020/02/11 18:16:00 p0 (100, 32, 14, 14)
2020/02/11 18:16:00 p2 shape (100, 128, 3, 3)
2020/02/11 18:16:00 r2 shape (100, 1152)
2020/02/11 18:16:00 l2 shape (100, 1152) | (1152, 625)
2020/02/11 18:16:00 l3 name Dropout 0.55(%15) :: Matrix float64 | a3 name ReLU(%14) :: Matrix float64
2020/02/11 18:16:00 DONE
panic: Failed to load module "sigmoid64" data for Device GPU(0) context 475055283029: InvalidPtx

goroutine 1 [running]:
gorgonia.org/gorgonia.(*tapeMachine).loadStdLib(0xc0000cd680)
        .../go/src/gorgonia.org/gorgonia/vm_tape_cuda.go:59 +0x289
gorgonia.org/gorgonia.(*tapeMachine).init(0xc0000cd680)
        .../go/src/gorgonia.org/gorgonia/vm_tape_cuda.go:39 +0xc4
gorgonia.org/gorgonia.NewTapeMachine(0xc000210140, 0xc00010de88, 0x1, 0x1, 0xc00019c1c0)
        .../go/src/gorgonia.org/gorgonia/vm_tape.go:69 +0x1ed
main.main()
        .../go/src/gorgonia.org/gorgonia/examples/convnet_cuda/main.go:247 +0x9e2
```
Every time i run example getting different module error.

Also getting this type of error:
```
2020/02/11 18:16:24 Using CUDA build
2020/02/11 18:16:24 gorgonia. true
2020/02/11 18:16:25 p0 (100, 32, 14, 14)
2020/02/11 18:16:25 p2 shape (100, 128, 3, 3)
2020/02/11 18:16:25 r2 shape (100, 1152)
2020/02/11 18:16:25 l2 shape (100, 1152) | (1152, 625)
2020/02/11 18:16:25 l3 name Dropout 0.55(%15) :: Matrix float64 | a3 name ReLU(%14) :: Matrix float64
2020/02/11 18:16:25 DONE
panic: Failed to load module "elemunaryop" data for Device GPU(0) context 475055283029: InvalidContext

goroutine 1 [running]:
gorgonia.org/gorgonia.(*tapeMachine).loadStdLib(0xc000125560)
        .../go/src/gorgonia.org/gorgonia/vm_tape_cuda.go:59 +0x289
gorgonia.org/gorgonia.(*tapeMachine).init(0xc000125560)
        .../go/src/gorgonia.org/gorgonia/vm_tape_cuda.go:39 +0xc4
gorgonia.org/gorgonia.NewTapeMachine(0xc000148000, 0xc0000fbe88, 0x1, 0x1, 0xc000117f40)
        .../go/src/gorgonia.org/gorgonia/vm_tape.go:69 +0x1ed
main.main()
        .../go/src/gorgonia.org/gorgonia/examples/convnet_cuda/main.go:247 +0x9e2
```

CUDA version: 10.2.89-3

**Comment by chewxy** [comment]
You need to run the `gencuda` program: 

```
$ go install gorgonia.org/gorgonia/cmd/gencuda
$ gencuda
```

**Comment by chewxy** [comment]
This is due to the fact that CUDA generates specialized code depending on which graphics card you have, and there are wayyyyyyyy too many types of graphics cards out there to add build tags for

**Comment by dimuls** [comment]
but there is no `gencuda` in `cmd`:
```
ls ~/go/src/gorgonia.org/gorgonia/cmd/
cudagen  genapi  gencudaengine
```
I tried to install `cudagen` and `gencudaengine` and run them. Still getting same error.

**Comment by chewxy** [comment]
As noticed by @owulveryck , `gencuda` only works when `GO111MODULE=off` and a `GOPATH` is set. 

A new issue has been filed on this #380. 

Let me know if `gencuda` works

**Comment by dimuls** [comment]
Able to run example with `GO111MODULE=off` hack, thank you. But i used `cudagen` not `gencuda`.

**Comment by dimuls** [comment]
@chewxy tried CUDA on my own cnn and constantly getting NaNs in output after 1 or 2 batches in first epoch. If i try run this code on CPU everything is ok. Why i'm getting this NaNs in CUDA?

**Comment by cfgt** [comment]
@dimuls unfortunately you have probably run into the issue described at #297 which is currently being worked on.

**Comment by chewxy** [comment]
I'm trying real hard to replicate #297 but so far everytime I try on a fresh instance, it works and I can't replicate it. 

@dimuls - got code, and what versions of CUDA and CuDNN are you running?

p/s: yes, it's `cudagen`, I get my names mistaken all the time

**Comment by dimuls** [comment]
@chewxy CUDA: 10.2.89-3, CUDNN: 7.6.5.32-3

**Comment by zachcoleman** [comment]
I'm having a hard time getting this same example to work as well. I can pass the _cu/cmd/cuda_test_ and can generate the _cudamodules.go_ (maybe this is in wrong place?) from _cudagen_ however when I try to run the _examples/convnet_cuda_ its saying gorgonia.CUDA is false:
```
2020/05/01 10:02:02 gorgonia. false
2020/05/01 10:02:03 p0 (100, 32, 14, 14)
2020/05/01 10:02:03 p2 shape (100, 128, 3, 3)
2020/05/01 10:02:03 r2 shape (100, 1152)
2020/05/01 10:02:03 l2 shape (100, 1152) | (1152, 625)
2020/05/01 10:02:03 l3 name ÷ false(%37, %35) :: Matrix float64 | a3 name ⊙ false(%31, %32) :: Matrix float64
2020/05/01 10:02:03 DONE
2020/05/01 10:02:03 m.out.Shape (100, 10), y.Shape (100, 10)
2020/05/01 10:02:03 Batches 600
Epoch 0 0 / 600 [------------------------------------------------------]   0.00%2020/05/01 10:02:03 Cost 4.397836673032081
```
It then prints out weights, losses, etc. and finall prints errors:

```
panic: runtime error: index out of range [-1]

goroutine 294 [running]:
gorgonia.org/gorgonia.(*maxPoolDiffOp).f64s(0xc000062600, 0x64, 0x80, 0x3, 0x3, 0x31, 0x9, 0x9, 0xc023cdc000, 0x99200, ...)
        C:/Users/zacha/go/src/gorgonia.org/gorgonia/op_nn.go:1075 +0x28a
gorgonia.org/gorgonia.(*maxPoolDiffOp).do(0xc000062600, 0xf26960, 0xc0001fa5a0, 0xf26960, 0xc00062c240, 0xf26960, 0xc00062c360, 0xf26960, 0xc00062c6c0)
        C:/Users/zacha/go/src/gorgonia.org/gorgonia/op_nn.go:1023 +0x3a9
gorgonia.org/gorgonia.(*maxPoolDiffOp).Do(0xc000062600, 0xc0003260c0, 0x3, 0x4, 0x1, 0x1, 0x2, 0x4)
        C:/Users/zacha/go/src/gorgonia.org/gorgonia/op_nn.go:946 +0x294
gorgonia.org/gorgonia.(*execOp).exec(0xc01b3c19f0, 0xc01b36a000, 0x0, 0x0)
        C:/Users/zacha/go/src/gorgonia.org/gorgonia/vm_tape_nocuda.go:62 +0xd0a
gorgonia.org/gorgonia.(*tapeMachine).runall(0xc01b36a000, 0xc000618000, 0xc000618060)
        C:/Users/zacha/go/src/gorgonia.org/gorgonia/vm_tape.go:236 +0x115
created by gorgonia.org/gorgonia.(*tapeMachine).RunAll
        C:/Users/zacha/go/src/gorgonia.org/gorgonia/vm_tape.go:208 +0x136
exit status 2
```

I don't know what I'm missing here and it may be really obvious so I apologize in advance. Any help would be much appreciated. For the record, I am on Windows.
