### ISSUE TITLE
convnet with cuda (v11) support not working

### ISSUE THREAD

**Issue by bh90210** [gorgonia/gorgonia#540]
hello there,

I am trying to make convnet cuda example work with CUDA v11.8 and it doesn't work.

It either ignored cuda and runs on CPU or it crashes with `index out of range [-1]`:
```
/gorgonia/examples/convnet_cuda$ time go run -tags='CUDA'  main.go -epochs 1 2
Epoch 0 4 / 600 [>----------------------------------------------]   0.67% 04m58spanic: runtime error: index out of range [-1]

goroutine 27378 [running]:
gorgonia.org/gorgonia.(*maxPoolDiffOp).f64s(0x8?, 0x64, 0x80, 0x3?, 0x3?, 0x31, 0x9, 0x9, {0xc002200000, 0x99200, ...}, ...)
        /go/pkg/mod/gorgonia.org/gorgonia@v0.9.15/op_nn.go:1075 +0x365
gorgonia.org/gorgonia.(*maxPoolDiffOp).do(0xc0000da600, {0xeba638, 0xc01d298800}, {0xeba638, 0xc01d30c300}, {0xeba638, 0xc01d30c400}, {0xeba638, 0xc01cd20900})
        /go/pkg/mod/gorgonia.org/gorgonia@v0.9.15/op_nn.go:1023 +0x368
gorgonia.org/gorgonia.(*maxPoolDiffOp).UsePreallocDo(0xc0000be0f0?, {0xeb23d0, 0xc01d298800}, {0xc01cff4040?, 0x1?, 0x1?})
        /go/pkg/mod/gorgonia.org/gorgonia@v0.9.15/op_nn.go:973 +0xc7
gorgonia.org/gorgonia.(*execOp).exec(0xc01b455a40, 0xc0000be0f0)
        /go/pkg/mod/gorgonia.org/gorgonia@v0.9.15/vm_tape_nocuda.go:60 +0x43a
gorgonia.org/gorgonia.(*tapeMachine).runall(0xc0000be0f0, 0x0?, 0x0?)
        /go/pkg/mod/gorgonia.org/gorgonia@v0.9.15/vm_tape.go:235 +0x102
created by gorgonia.org/gorgonia.(*tapeMachine).RunAll
        /go/pkg/mod/gorgonia.org/gorgonia@v0.9.15/vm_tape.go:208 +0x158
exit status 2

real    0m3.220s
user    0m8.269s
sys     0m0.492s
```

I have ran `codagen` successfully and I am wondering if I simply should switch to CUDA v10.2 since it is already tested against as stated on the [website](https://gorgonia.org/tutorials/mnist-cuda/).

Relates to #522 #515 and even potentially as far as #376.

**Comment by chewxy** [comment]
for now, switch to cuda 10.2 . CUDA11 is still being worked on and it's been difficult for me given that I'm sick fairly often nowadays

**Comment by bh90210** [comment]
I was wondering if you could give any pointers (code, walk-though, previous PR...) as to what is needed. If it is not insanely convoluted I have some spare time, I could give a try for educational purposes.
